In [15]:
# example 1
import tensorflow as tf

# data
x = tf.Variable([[1, 1],
                 [1, 1]], dtype=tf.float32)
  
with tf.GradientTape() as t:
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

# compute derivative
dz_dx = t.gradient(z, x)

# print out
print(x.numpy())
print(dz_dx)

[[1. 1.]
 [1. 1.]]
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [9]:
import tensorflow as tf

# data
x = tf.Variable([3.0], dtype=tf.float32)

# trace
with tf.GradientTape(persistent=True) as t:
    y = x * x
    z = y * y

# compute derivative
dz_dx = t.gradient(z, x)
dy_dx = t.gradient(y, x)

# print out
print(dz_dx)
print(dy_dx)

tf.Tensor([108.], shape=(1,), dtype=float32)
tf.Tensor([6.], shape=(1,), dtype=float32)


In [10]:
x = tf.Variable([3.0], dtype=tf.float32)
with tf.GradientTape(persistent=True) as t:
    y = x * x
    z = y * y
    
dz_dx = t.gradient(z, x)  # 108.0 (4*x^3 at x = 3)
dy_dx = t.gradient(y, x)  # 6.0
del t  # Drop the reference to the tape

print(dz_dx)
print(dy_dx)

tf.Tensor([108.], shape=(1,), dtype=float32)
tf.Tensor([6.], shape=(1,), dtype=float32)


In [11]:
# data
x = tf.Variable([1.0], dtype=tf.float32)

# trace
with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y = x*x*x
    
    # compute derivative using t2
    dy_dx = t2.gradient(y, x)

# compute derivative using t1
d2y_dx2 = t1.gradient(dy_dx, x)

# print out
print(dy_dx)
print(d2y_dx2)

tf.Tensor([3.], shape=(1,), dtype=float32)
tf.Tensor([6.], shape=(1,), dtype=float32)


In [12]:
import tensorflow as tf

# variable
x = tf.Variable([2.0], dtype=tf.float32)

# trace
with tf.GradientTape() as tape:    
    # construct functions
    g_x = -3*x + 4
    h_g =  2*g_x + 1

# compute derivative
dh_dx = tape.gradient(h_g, x)

# print out
print(dh_dx)

tf.Tensor([-6.], shape=(1,), dtype=float32)


In [13]:
import tensorflow as tf

# variable
x = tf.Variable([1.0], dtype=tf.float32)

# trace
with tf.GradientTape() as tape:
    # construct functions
    g_x = x*x + 1
    h_g = tf.exp(g_x)

# compute derivative
dh_dx = tape.gradient(h_g, x)

# print out
print(dh_dx)

tf.Tensor([14.778112], shape=(1,), dtype=float32)


In [14]:
import tensorflow as tf

# variable
x = tf.Variable([1.0], dtype=tf.float32)

# trace
with tf.GradientTape() as tape:    
    # construct functions
    g_x = tf.math.cos(x*x*tf.exp(x) + 2*x)
    h_g = tf.exp(g_x)*tf.math.sin(tf.math.sqrt(g_x))

# compute derivative
dh_dx = tape.gradient(h_g, x)

# print out
print(dh_dx)

tf.Tensor([67.120346], shape=(1,), dtype=float32)
