## RNN

In [1]:
import torch
import torch.nn as nn

embedding_dim, hidden_dim = 3, 4
rnn = nn.RNN(embedding_dim, 
             hidden_dim,
             batch_first=True)

In [3]:
input_sample = torch.Tensor([[[-0.88,  0.81,  0.77],
                              [-1.27,  0.84,  0.04]]])

outputs, hidden = rnn(input_sample)
print(outputs)

tensor([[[ 0.5336,  0.7105, -0.0345,  0.2959],
         [ 0.4654,  0.7062, -0.1752,  0.5754]]], grad_fn=<TransposeBackward1>)


## Using For Loop

In [4]:
# for the first word
first_word = torch.Tensor([[[-0.88,  0.81,  0.77]]])

outputs, hidden = rnn(first_word)
print(outputs)

tensor([[[ 0.5336,  0.7105, -0.0345,  0.2959]]], grad_fn=<TransposeBackward1>)


In [5]:
# for the second word
second_word = torch.Tensor([[[-1.27,  0.84,  0.04]]])

outputs, hidden = rnn(second_word, hidden)
print(outputs)

tensor([[[ 0.4654,  0.7062, -0.1752,  0.5754]]], grad_fn=<TransposeBackward1>)
